name: drive_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.3.0
  flutter_local_notifications: ^17.0.0

  cupertino_icons: ^1.0.2
  
  # HTTP requests
  http: ^1.1.0
  
  # Internationalization
  intl: ^0.19.0

  get: ^4.7.2
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Country code picker
  country_code_picker: ^3.0.0
  
  # Pin code input
  pin_code_fields: ^8.0.1
  
  # Loading animation
  loading_animation_widget: ^1.2.0+4
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Firebas
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7
  # Location
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # Image picker
  image_picker: ^1.0.4
  
  # URL launcher
  url_launcher: ^6.2.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
